spring:
    profiles:
      active:
       -dev

---
server:
    port: 8001
spring:
    profiles: dev
    application:
         name: eureka-client
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:6666/eureka/


---
spring:
    profiles: test
    application:
         name: config-test
